config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users
    root "pages#index"

    get 'search', to: 'search#search'

    resources :categories
    resources :posts
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  searchkick
  has_many :posts
  belongs_to :user

  scope :search_import, -> { includes( :posts )}

  def search_data
    super().merge!(posts: posts.map { |post| post.description }.join(' '))
  end
end

app/models/post.rb
class Post < ApplicationRecord
  searchkick
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true, uniqueness: true
  validates :last_name, :first_name, presence: true
  has_many :posts, dependent: :destroy
  has_many :categories, dependent: :destroy
  encrypts :first_name
  encrypts :last_name

  enum role: [:noob, :moderator, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  before_action :configure_permitted_parameters, if: :devise_controller?

  around_action :switch_locale


  protected

  def configure_permitted_parameters
    added_attrs = %i[first_name last_name email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  private
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale locale, &action
  end

  def locale_from_url
    locale = params[:locale]

    return locale if I18n.available_locales.map(&to_s).include?(locale)

    nil
  end

  def default_url_options
    { locale: I18n.locale}
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = Category.includes(:posts).order(created_at: :desc)
    @posts = Post.all
  end

  def show
    authorize @category
  end

  def new
    @category = Category.new
    authorize @category
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user
    authorize @category
    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @category
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @category
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :description, :parent_id)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.all
    authorize @post
  end

  def show
    authorize @post
  end

  def new
    @post = Post.new
    authorize @post
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    authorize @post

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @post
    respond_to do |format|

      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @post
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :description, :category_id)
    end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:term].nil?
      @result = []
    else
      @result = Searchkick.search(params[:term], models: [Post, Category])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/categories/_category.html.erb
<ul class="categories">
  <% collection.arrange.each do |category, sub_item| %>
    <li>
      <%= link_to category.name, category_path(category) %>
      <% if category.has_children? %>
        <%= render partial: "category", locals: { collection: category.children } %>
      <% end %>
      <% if category.posts.present? %>
        <ul class="categories">
          <% category.posts.each do |post| %>
            <li>
              <%= link_to post.name, post_path(post) %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>


  <div>
    <%= form.label :parent_id %>
    <%= form.collection_select :parent_id, Category.order(:name), :id, :name, include_blank: true %>
  </div>

  <div>
    <%= form.submit %>
    <%= link_to t('categories._form.cancel'), categories_path%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1> <%= t '.name'%></h1>

<%= render partial: "category", locals: { collection: Category.all } %>

app/views/categories/new.html.erb
<h1><%= t'.new_category' %></h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to t('.back_to'), categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>
<p>
  <strong><%= t '.name' %></strong>
  <%= @category.name %>
</p>

<p>
  <strong><%= t '.description' %></strong>
  <%= @category.description %>
</p>

<div>
  <%= link_to t('.edit'), edit_category_path(@category) %> |
  <%= link_to t('.back'), categories_path %>

  <%= button_to t('.destroy'), category_path(@category), method: :delete %>
</div>


<h2><%= t'.all_posts' %></h2>

<% @category.posts.each do |post| %>
  <div class="alert alert-light">
    <p>
      <%=  post.created_at %>
    </p>
    <p> <%= link_to post.name, post_path(post)%></p>
    <p><strong><%= post.user.first_name %></strong>: <%=post.description%> </p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <span class="btn btn-info"><%= current_user.role rescue  "Guest"%> </span>
  <span class="btn btn-info"><%= current_user.first_name rescue  ""%> </span>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
  <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
    <span class="fs-4"></span>
  </a>



  <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
    <span class="btn btn-light"><%= link_to t('application.home'), root_path%></span>
    <% if current_user %>
      <span class="btn btn-warning"><%= link_to "Go Content", categories_path %></span>
      <span class="btn btn-warning"><%= link_to t('application.new_category'), new_category_path %> </span>
      <span class="btn btn-warning"><%= link_to t('application.new_post'), new_post_path %> </span>
    <% end %>
  </nav>
</div>



<ul class="dropdown-menu">
  <% I18n.available_locales.each do |locale| %>
    <li>
      <% if I18n.locale == locale %>
        <%= tag.span t(locale), class: 'dropdown-item' %>
      <% else %>
        <%= link_to t(locale), root_path(locale: locale), class: 'dropdown-item' %>
      <% end %>
    </li>
  <% end %>
</ul>

<body>
<%= render 'search/form' %>
</body>


<body>
<main>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if current_user %>
    <%= button_to t('application.log_out'), destroy_user_session_path, method: :delete  %>
    <%= link_to t('application.account_set'), edit_user_registration_path %>
    <%= link_to "Go Content", categories_path %>
  <% else %>
    <li><h2>You need Authorization or Registered!</h2></li>
    <h3><%= link_to t('application.sign_in'), new_user_session_path%></h3>
    <h3><%= link_to t('application.sign_up'), new_user_registration_path%></h3>
  <% end %>

  <hr>
  <div class="container">
    <%= yield %>
  </div>
</main>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">

  <p>
    <strong>Name:</strong>
    <%= post.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1><%= t'post.new.new_post' %></h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>

  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", post_path(@post), method: :delete %>
</div>

app/views/search/_form.html.erb
<%= form_for :term, url: search_path, method: :get do |form|%>
  <p>
    <%= text_field_tag :term, params[:term] %>
    <%= submit_tag t '.search' , name: nil %>
  </p>
<% end %>

app/views/search/search.html.erb
<h2><%= t "search.search" %> <i><%= params[:term] %></i></h2>
<% if @result %>
  <ul class=»search_results»>
    <% @result.each do |result| %>
      <li>
        <h3>
            <% if result.class.name.to_s == "Category" %>
              <%=link_to result.try(:highlight).try(:name) ?
                           result.highlight.name[0].html_safe : result.name,
                         controller: "categories", action: "show", id: result.id %>
              <% else %>
              <%=link_to result.try(:highlight).try(:name) ?
                           result.highlight.name[0].html_safe : result.name,
                         controller: "posts", action: "show", id: result.id %>
              <% end %>
        </h3>
        <%if result.try(:highlight).try(:text)%>
          <% result.highlight.text.each do |snippet| %>
            <p><%=snippet.html_safe %>…</p>
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>Your search did not match any documents.</p>
<% end %>